### ISSUE TITLE
Exception when I press "Continue"

### ISSUE THREAD

**Issue by mifth** [GuilhermeGSousa/game-base-2D#5]
![image](https://github.com/GuilhermeGSousa/game-base-2D/assets/2251298/d914c300-ca56-4da7-83ea-51bbad176194)

**Comment by GuilhermeGSousa** [comment]
This would happen if you haven't saved a file before. That said, I think:
- This should have a guard to prevent crashing if no save is available
- Continue should disable itself if no save is available
I'll add these two fixes

**Comment by mifth** [comment]
Yeah, right. But there should be no exceptions and crashes in a game.
