### ISSUE TITLE
top_down_sample.tscn cannot run

### ISSUE THREAD

**Issue by lb1565387341** [GuilhermeGSousa/game-base-2D#8]
i select this scene then press F6,then find this error.my godot version is 4.2.1
![image](https://github.com/GuilhermeGSousa/game-base-2D/assets/16556310/8db0a893-abb4-49e5-9524-79a9663ee926)
![image](https://github.com/GuilhermeGSousa/game-base-2D/assets/16556310/625b2b94-223c-456b-be24-24a58c5fde75)
is that a bug?

**Comment by GuilhermeGSousa** [comment]
Hi there! Yes they changed it recently, adding `super.` is no longer required. That is also fixed on the latest version of that file if you want to try that one out.

**Comment by GuilhermeGSousa** [comment]
Oh makes sense! I'll update a fixed version to the asset store soon then.
